language: node_js
node_js:
- '4'
- '6'
- '7'
sudo: false
git:
  depth: 1
notifications:
  irc: irc.freenode.org#socket.io
matrix:
  include:
  - node_js: 'node'
    env: BROWSER_NAME=chrome BROWSER_VERSION=latest
  - node_js: 'node'
    env: BROWSER_NAME=safari BROWSER_VERSION=latest
  - node_js: 'node'
    env: BROWSER_NAME=firefox BROWSER_VERSION=latest
  - node_js: 'node'
    env: BROWSER_NAME=ie BROWSER_VERSION=6
  - node_js: 'node'
    env: BROWSER_NAME=ie BROWSER_VERSION=7
  - node_js: 'node'
    env: BROWSER_NAME=ie BROWSER_VERSION=8
  - node_js: 'node'
    env: BROWSER_NAME=ie BROWSER_VERSION=9
  - node_js: 'node'
    env: BROWSER_NAME=ie BROWSER_VERSION=10
  - node_js: 'node'
    env: BROWSER_NAME=ie BROWSER_VERSION=11
  - node_js: 'node'
    env: BROWSER_NAME=microsoftedge BROWSER_VERSION=latest
  - node_js: 'node'
    env: BROWSER_NAME=iphone BROWSER_VERSION=8.4
  - node_js: 'node'
    env: BROWSER_NAME=iphone BROWSER_VERSION=9.2
  - node_js: 'node'
    env: BROWSER_NAME=iphone BROWSER_VERSION=10.0
  - node_js: 'node'
    env: BROWSER_NAME=android BROWSER_VERSION=4.4
  - node_js: 'node'
    env: BROWSER_NAME=android BROWSER_VERSION=5.1
  - node_js: 'node'
    env: BROWSER_NAME=ipad BROWSER_VERSION=9.3
  - node_js: 'node'
    env: BROWSER_NAME=ipad BROWSER_VERSION=10.0
